name: big组件
description: testlll
keywords:
  - websocket
  - network
  - 张玉洁的标签
license: MIT                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD
homepage: https://www.taobao.com/
source_file:
  - src/*.c

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
